// Do not edit. This file is machine generated by the Resource DLL Wizard.

library TestCore;

{ITE} {DFMFileType} {Unit1.dfm}
{ITE} {RCFileType} {Win32\Debug\TestCore_DRC.rc}

{$R 'Unit1.dfm' 'Form1:TForm'}
{$R 'Win32\Debug\TestCore_DRC.res' 'Win32\Debug\TestCore_DRC.rc'}

{$E RUS}

begin
end.
