// ************************************************************************ //
// WARNING                                                                    
// -------                                                                    
// The types declared in this file were generated from data read from a       
// Type Library. If this type library is explicitly or indirectly (via        
// another type library referring to this type library) re-imported, or the   
// 'Refresh' command of the Type Library Editor activated while editing the   
// Type Library, the contents of this file will be regenerated and all        
// manual modifications will be lost.                                         
// ************************************************************************ //

// $Rev: 98350 $
// File generated on 12.11.2020 10:55:05 from Type Library described below.

// ************************************************************************  //
// Type Lib: H:\RADStudioProjects\Evgeny\PluginSystemTest\SDKTypeLib\PluginAPIWrapper.tlb (1)
// LIBID: {59B571B1-F6B7-4198-92AD-7895CBAFBE40}
// LCID: 0
// Helpfile: 
// HelpString: 
// DepndLst: 
//   (1) v2.0 stdole, (C:\Windows\System32\stdole2.tlb)
// SYS_KIND: SYS_WIN32
// Cmdline:
//   "H:\RAD\Studio\21\bin64\tlibimp.exe"  -C -P -D"H:\RADStudioProjects\Evgeny\PluginSystemTest\SDK" -Pt -XM "H:\RADStudioProjects\Evgeny\PluginSystemTest\SDKTypeLib\PluginAPIWrapper.tlb"
// ************************************************************************ //
#ifndef   PluginAPI_OCXH
#define   PluginAPI_OCXH

#pragma option push -b -w-inl -w-8118
#pragma pack(push, 4)

#include <Vcl.OleCtrls.hpp>
#include <Vcl.OleServer.hpp>
#if !defined(__UTILCLS_H)
#include <utilcls.h>
#endif
#if !defined(__UTILCLS_H_VERSION) || (__UTILCLS_H_VERSION < 0x0700)
//
// The code generated by the TLIBIMP utility or the Import|TypeLibrary 
// and Import|ActiveX feature of C++Builder rely on specific versions of
// the header file UTILCLS.H found in the INCLUDE\VCL directory. If an 
// older version of the file is detected, you probably need an update/patch.
//
#error "This file requires a newer version of the header UTILCLS.H" \
       "You need to apply an update/patch to your copy of C++Builder"
#endif
#include <olectl.h>
#include <ocidl.h>
#if !defined(_NO_VCL)
#include <System.Win.StdVCL.hpp>
#endif  //   _NO_VCL
#include <ocxproxy.h>

#include "PluginAPI_TLB.h"
namespace Pluginapi_tlb
{

// *********************************************************************//
// HelpString: 
// Version:    1.0
// *********************************************************************//

};     // namespace Pluginapi_tlb

#if !defined(NO_IMPLICIT_NAMESPACE_USE)
using  namespace Pluginapi_tlb;
#endif

#pragma pack(pop)
#pragma option pop

#endif // PluginAPI_OCXH
